name: Deploy to S3

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4.2.2

      - name: Install Node.js
        uses: actions/setup-node@v3.9.1

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::351609396646:role/github-actions-access-portfolio-s3
      - name: S3 Sync
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --delete
          source-dir: build
        env:
          AWS_S3_BUCKET: noah-pursell-personal-website
