name: Deploy to S3

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4.2.2

      - name: Install Node.js
        uses: actions/setup-node@v3.9.1

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::351609396646:role/github-actions-access-portfolio-s3
      - name: S3 Sync
        run: aws s3 sync build/ s3://noah-pursell-personal-website --delete
